# Generated by Django 4.2.17 on 2024-12-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_temperaturenotificationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
